import type {Metadata} from "next";

// eslint-disable-next-line import/order
import {Inter} from "next/font/google";

import "./globals.css";
import React from "react";

import {NextAuthProvider, ReactQueryProvider} from "~/app/providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
